name: cancer-sc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - scanpy>=1.9.0
  - pandas>=2.0.0
  - numpy>=1.23.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - scipy>=1.9.0
  - scikit-learn>=1.0.0
  - jupyterlab>=3.0.0
  - ipykernel>=6.0.0
  - pip
  - pip:
    - leidenalg
